### ISSUE TITLE
镜像服务关闭了吗？可否将set_mirror.sh这个脚本开源一下

### ISSUE THREAD

**Issue by Paper-Dragon** [DaoCloud/docker-mirror#2]
https://get.daocloud.io/docker

**Comment by yankay** [comment]
这个脚本，我记是 https://get.docker.com/，将其中的 海外url 替换为 国内 url。
但现在不一定可以工作

**Comment by Paper-Dragon** [comment]
感谢回复，我需要的是这个脚本，https://get.daocloud.io/daotools/set_mirror.sh，我自己做了个镜像加速，如果能有这个脚本，那我就不需要重新写一份了。

**Comment by yankay** [comment]
这个 repo 已经 deprecated ，  [加速三剑客](https://github.com/DaoCloud/public-image-mirror)  可以做镜像加速。应该能够满足你的需要。

**Comment by Paper-Dragon** [comment]
好的谢谢，我去找一下。
